grid_search:
  module: sklearn.model_selection
  class: "GridSearchCV"
  params:
    cv: 2
    verbose: 2
    n_jobs: -1

model_selection:
  module_0:
    class: XGBRegressor
    module: xgboost
    params:
      seed: 20
    search_param_grid:
      learning_rate:
      - 0.01
      - 0.1
      n_estimators:
      - 100
      - 200
      max_depth:
      - 3
      - 6
  module_1:
    class: CatBoostRegressor
    module: catboost
    params:
      loss_function: RMSE
    search_param_grid:
      iterations:
      - 100
      - 200
      learning_rate:
      - 0.03
      - 0.1
      depth:
      - 4
      - 8
      l2_leaf_reg:
      - 0.5
      - 3
  module_2:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      min_samples_leaf: 2
    search_param_grid:
      min_samples_leaf:
      - 4
      - 6
      - 12
      n_estimators:
      - 100
      - 200
      max_depth:
      - 2
      - 4
      - 6

